version: "3.8"

# SIEMBox - Security Information and Event Management System
# This docker-compose file defines all services required to run SIEMBox

services:
  # Database service - PostgreSQL for storing logs, alerts, and configuration
  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=${DB_USER:-siembox}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-changeme}
      - POSTGRES_DB=siembox
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - siem_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -U ${DB_USER:-siembox} -d siembox"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s
    # No external port by default - accessed by other services internally

  # Redis service - Used for caching and rate limiting
  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
    networks:
      - siem_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    # No external port by default - accessed by other services internally

  # API Gateway - Central coordination point for all services
  api:
    image: ghcr.io/cladkins/siembox/api:latest
    ports:
      - "${API_PORT:-8080}:8080"
    environment:
      - DB_HOST=db
      - DB_USER=${DB_USER:-siembox}
      - DB_PASSWORD=${DB_PASSWORD:-changeme}
      - DB_NAME=siembox
      - JWT_SECRET=${JWT_SECRET:-change_this_in_production}
      # Internal port remains 8080 - doesn't need to be configurable
    networks:
      - siem_network
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Detection Service - Manages Sigma rules and analyzes logs
  detection:
    image: ghcr.io/cladkins/siembox/detection:latest
    ports:
      - "${DETECTION_PORT:-8001}:8000"
    volumes:
      - sigma_rules:/app/rules
    environment:
      - SIGMA_RULES_PATH=/app/rules
      # Internal port is 8000, external port is configurable
    networks:
      - siem_network
    depends_on:
      api:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    user: "65534:65534"
    init: true

  # IP Lookup Service - Provides IP geolocation and threat intelligence
  iplookup:
    image: ghcr.io/cladkins/siembox/iplookup:latest
    ports:
      - "${IPLOOKUP_PORT:-8002}:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      # Internal port is 8000, external port is configurable
    networks:
      - siem_network
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health 2>/dev/null"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # VPS Audit Service - Performs security audits on remote servers
  vps-audit:
    image: ghcr.io/cladkins/siembox/vps-audit:latest
    ports:
      - "${VPS_AUDIT_PORT:-8004}:8004"
    environment:
      - POSTGRES_USER=${DB_USER:-siembox}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-changeme}
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=siembox
      - ENCRYPTION_KEY=${ENCRYPTION_KEY:-change_this_in_production}
      # Both internal and external ports are 8004
    networks:
      - siem_network
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8004/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - ssh_keys:/root/.ssh

  # Frontend Service - Web interface for the system
  frontend:
    image: ghcr.io/cladkins/siembox/frontend:latest
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    environment:
      # These URLs need to use the remote host's address
      - REACT_APP_API_URL=http://${HOST_ADDRESS}:${API_PORT:-8080}
      - REACT_APP_DETECTION_URL=http://${HOST_ADDRESS}:${DETECTION_PORT:-8001}
      - REACT_APP_IPLOOKUP_URL=http://${HOST_ADDRESS}:${IPLOOKUP_PORT:-8002}
      - REACT_APP_VPS_AUDIT_URL=http://${HOST_ADDRESS}:${VPS_AUDIT_PORT:-8004}
    networks:
      - siem_network
    depends_on:
      api:
        condition: service_healthy
      detection:
        condition: service_healthy
      vps-audit:
        condition: service_healthy

  # Fluent Bit Collector Service
  fluent-bit:
    image: ghcr.io/cladkins/siembox/fluent-bit:latest # Use custom SIEMBox image
    ports:
      - "${SYSLOG_UDP_PORT:-5514}:5514/udp"
      - "${SYSLOG_TCP_PORT:-5514}:5514/tcp"
      # Expose Fluent Bit's monitoring port (optional)
      - "2020:2020"
    # Explicitly tell Fluent Bit which config file to use
    command: /fluent-bit/bin/fluent-bit -c /fluent-bit/etc/fluent-bit.conf
    networks:
      - siem_network
    depends_on:
      api:
        condition: service_healthy
    # Add a simple healthcheck (optional, checks if the process is running)
    healthcheck:
      test: ["CMD-SHELL", "pidof fluent-bit"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  siem_network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  sigma_rules:
  ssh_keys: