-- SIEMBox Initial Database Schema
-- This file contains all the tables needed for the SIEM system

-- Users table for authentication and access control
CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL DEFAULT 'viewer', -- 'admin', 'analyst', 'viewer'
    enabled BOOLEAN DEFAULT true,
    last_login TIMESTAMP,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

-- Sessions table for session management
CREATE TABLE IF NOT EXISTS sessions (
    id SERIAL PRIMARY KEY,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    token VARCHAR(255) NOT NULL UNIQUE,
    expires_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP DEFAULT NOW()
);

-- Raw syslog messages as received
CREATE TABLE IF NOT EXISTS raw_logs (
    id SERIAL PRIMARY KEY,
    timestamp TIMESTAMP NOT NULL,
    raw_message TEXT NOT NULL,
    source_ip VARCHAR(45) NOT NULL,
    facility INTEGER,
    severity INTEGER,
    hostname VARCHAR(255),
    created_at TIMESTAMP DEFAULT NOW()
);

-- Parsers for transforming raw logs into structured data
CREATE TABLE IF NOT EXISTS parsers (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    description TEXT,
    enabled BOOLEAN DEFAULT true,
    priority INTEGER DEFAULT 100, -- Lower number = higher priority
    parser_type VARCHAR(50) NOT NULL, -- 'regex', 'grok', 'json'
    pattern TEXT NOT NULL,
    field_mappings JSONB NOT NULL, -- Maps pattern groups to field names
    test_samples JSONB, -- Sample logs for testing
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

-- Parsed logs with structured data
CREATE TABLE IF NOT EXISTS parsed_logs (
    id SERIAL PRIMARY KEY,
    raw_log_id INTEGER REFERENCES raw_logs(id) ON DELETE CASCADE,
    parser_id INTEGER REFERENCES parsers(id) ON DELETE SET NULL,
    parsed_data JSONB NOT NULL,
    timestamp TIMESTAMP NOT NULL,
    source_ip VARCHAR(45) NOT NULL,
    event_type VARCHAR(100), -- e.g., 'ssh_login', 'http_request', 'firewall_block'
    created_at TIMESTAMP DEFAULT NOW()
);

-- Detection rules for identifying security events
CREATE TABLE IF NOT EXISTS detection_rules (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    description TEXT,
    enabled BOOLEAN DEFAULT true,
    severity VARCHAR(20) NOT NULL, -- 'low', 'medium', 'high', 'critical'
    rule_yaml TEXT NOT NULL,
    rule_logic JSONB NOT NULL, -- Parsed YAML for quick access
    tags TEXT[], -- For categorization ['ssh', 'brute-force', 'authentication']
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

-- Alerts generated by detection rules
CREATE TABLE IF NOT EXISTS alerts (
    id SERIAL PRIMARY KEY,
    rule_id INTEGER REFERENCES detection_rules(id) ON DELETE CASCADE,
    parsed_log_id INTEGER REFERENCES parsed_logs(id) ON DELETE SET NULL,
    severity VARCHAR(20) NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    matched_data JSONB NOT NULL, -- Data that matched the rule
    status VARCHAR(20) DEFAULT 'new', -- 'new', 'investigating', 'closed', 'false_positive'
    assigned_to INTEGER REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_raw_logs_timestamp ON raw_logs(timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_raw_logs_source_ip ON raw_logs(source_ip);
CREATE INDEX IF NOT EXISTS idx_raw_logs_created_at ON raw_logs(created_at DESC);

CREATE INDEX IF NOT EXISTS idx_parsed_logs_timestamp ON parsed_logs(timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_parsed_logs_source_ip ON parsed_logs(source_ip);
CREATE INDEX IF NOT EXISTS idx_parsed_logs_event_type ON parsed_logs(event_type);
CREATE INDEX IF NOT EXISTS idx_parsed_logs_created_at ON parsed_logs(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_parsed_data_gin ON parsed_logs USING GIN(parsed_data);

CREATE INDEX IF NOT EXISTS idx_parsers_enabled ON parsers(enabled);
CREATE INDEX IF NOT EXISTS idx_parsers_priority ON parsers(priority);

CREATE INDEX IF NOT EXISTS idx_rules_enabled ON detection_rules(enabled);
CREATE INDEX IF NOT EXISTS idx_rules_severity ON detection_rules(severity);
CREATE INDEX IF NOT EXISTS idx_rules_tags ON detection_rules USING GIN(tags);

CREATE INDEX IF NOT EXISTS idx_alerts_created_at ON alerts(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_alerts_severity ON alerts(severity);
CREATE INDEX IF NOT EXISTS idx_alerts_status ON alerts(status);
CREATE INDEX IF NOT EXISTS idx_alerts_rule_id ON alerts(rule_id);

CREATE INDEX IF NOT EXISTS idx_sessions_token ON sessions(token);
CREATE INDEX IF NOT EXISTS idx_sessions_expires_at ON sessions(expires_at);

-- Comments for documentation
COMMENT ON TABLE users IS 'User accounts with role-based access control';
COMMENT ON TABLE sessions IS 'Active user sessions for authentication';
COMMENT ON TABLE raw_logs IS 'Raw syslog messages as received from sources';
COMMENT ON TABLE parsers IS 'Custom parsers for transforming raw logs';
COMMENT ON TABLE parsed_logs IS 'Structured logs after parser processing';
COMMENT ON TABLE detection_rules IS 'YAML-based detection rules for security events';
COMMENT ON TABLE alerts IS 'Security alerts generated by detection rules';

COMMENT ON COLUMN users.role IS 'Access level: admin, analyst, or viewer';
COMMENT ON COLUMN parsers.parser_type IS 'Type of parser: regex, grok, or json';
COMMENT ON COLUMN parsers.priority IS 'Parser priority (lower = higher priority)';
COMMENT ON COLUMN detection_rules.severity IS 'Alert severity: low, medium, high, or critical';
COMMENT ON COLUMN alerts.status IS 'Alert status: new, investigating, closed, or false_positive';
