-- SIEMBox Initial Database Schema
-- This file contains all the tables needed for the SIEM system

-- Enable pgcrypto extension for cryptographic functions (MD5, SHA256)
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Users table for authentication and access control
CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL DEFAULT 'viewer', -- 'admin', 'analyst', 'viewer', 'operator'
    enabled BOOLEAN DEFAULT true,
    last_login TIMESTAMP,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

-- Sessions table for session management
CREATE TABLE IF NOT EXISTS sessions (
    id SERIAL PRIMARY KEY,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    token VARCHAR(255) NOT NULL UNIQUE,
    expires_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP DEFAULT NOW()
);

-- Raw syslog messages as received
CREATE TABLE IF NOT EXISTS raw_logs (
    id SERIAL PRIMARY KEY,
    timestamp TIMESTAMP NOT NULL,
    raw_message TEXT NOT NULL,
    source_ip VARCHAR(45) NOT NULL,
    facility INTEGER,
    severity INTEGER,
    hostname VARCHAR(255),
    app_name VARCHAR(255),
    shipper_id VARCHAR(50), -- Short identifier from log shipper for tracing logs back to source
    created_at TIMESTAMP DEFAULT NOW()
);

-- Parsers for transforming raw logs into structured data
CREATE TABLE IF NOT EXISTS parsers (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    description TEXT,
    enabled BOOLEAN DEFAULT true,
    priority INTEGER DEFAULT 100, -- Lower number = higher priority
    parser_type VARCHAR(50) NOT NULL, -- 'regex', 'grok', 'json'
    pattern TEXT NOT NULL,
    field_mappings JSONB NOT NULL, -- Maps pattern groups to field names
    test_samples JSONB, -- Sample logs for testing
    event_type VARCHAR(100), -- Optional: event type for parsed logs (e.g., 'ssh_failed_login', 'http_request')
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

-- Parsed logs with structured data
CREATE TABLE IF NOT EXISTS parsed_logs (
    id SERIAL PRIMARY KEY,
    raw_log_id INTEGER REFERENCES raw_logs(id) ON DELETE CASCADE,
    parser_id INTEGER REFERENCES parsers(id) ON DELETE SET NULL,
    parsed_data JSONB NOT NULL,
    timestamp TIMESTAMP NOT NULL,
    source_ip VARCHAR(45) NOT NULL,
    event_type VARCHAR(100), -- e.g., 'ssh_login', 'http_request', 'firewall_block'
    created_at TIMESTAMP DEFAULT NOW()
);

-- Detection rules for identifying security events
CREATE TABLE IF NOT EXISTS detection_rules (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    description TEXT,
    enabled BOOLEAN DEFAULT true,
    severity VARCHAR(20) NOT NULL, -- 'low', 'medium', 'high', 'critical'
    rule_yaml TEXT NOT NULL,
    rule_logic JSONB NOT NULL, -- Parsed YAML for quick access
    tags TEXT[], -- For categorization ['ssh', 'brute-force', 'authentication']
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

-- Alerts generated by detection rules
CREATE TABLE IF NOT EXISTS alerts (
    id SERIAL PRIMARY KEY,
    rule_id INTEGER REFERENCES detection_rules(id) ON DELETE CASCADE,
    parsed_log_id INTEGER REFERENCES parsed_logs(id) ON DELETE SET NULL,
    severity VARCHAR(20) NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    matched_data JSONB NOT NULL, -- Data that matched the rule
    status VARCHAR(20) DEFAULT 'new', -- 'new', 'investigating', 'closed', 'false_positive'
    assigned_to INTEGER REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

-- IP whitelist for admin access control and rule exceptions
CREATE TABLE IF NOT EXISTS ip_whitelist (
    id SERIAL PRIMARY KEY,
    ip_address CIDR NOT NULL,
    description TEXT,
    rule_id VARCHAR(50),
    created_by INTEGER REFERENCES users(id),
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_raw_logs_timestamp ON raw_logs(timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_raw_logs_source_ip ON raw_logs(source_ip);
CREATE INDEX IF NOT EXISTS idx_raw_logs_app_name ON raw_logs(app_name);
CREATE INDEX IF NOT EXISTS idx_raw_logs_created_at ON raw_logs(created_at DESC);

CREATE INDEX IF NOT EXISTS idx_parsed_logs_timestamp ON parsed_logs(timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_parsed_logs_source_ip ON parsed_logs(source_ip);
CREATE INDEX IF NOT EXISTS idx_parsed_logs_event_type ON parsed_logs(event_type);
CREATE INDEX IF NOT EXISTS idx_parsed_logs_created_at ON parsed_logs(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_parsed_data_gin ON parsed_logs USING GIN(parsed_data);

CREATE INDEX IF NOT EXISTS idx_parsers_enabled ON parsers(enabled);
CREATE INDEX IF NOT EXISTS idx_parsers_priority ON parsers(priority);

CREATE INDEX IF NOT EXISTS idx_rules_enabled ON detection_rules(enabled);
CREATE INDEX IF NOT EXISTS idx_rules_severity ON detection_rules(severity);
CREATE INDEX IF NOT EXISTS idx_rules_tags ON detection_rules USING GIN(tags);

CREATE INDEX IF NOT EXISTS idx_alerts_created_at ON alerts(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_alerts_severity ON alerts(severity);
CREATE INDEX IF NOT EXISTS idx_alerts_status ON alerts(status);
CREATE INDEX IF NOT EXISTS idx_alerts_rule_id ON alerts(rule_id);

CREATE INDEX IF NOT EXISTS idx_sessions_token ON sessions(token);
CREATE INDEX IF NOT EXISTS idx_sessions_expires_at ON sessions(expires_at);

CREATE INDEX IF NOT EXISTS idx_ip_whitelist_cidr ON ip_whitelist USING GIST (ip_address inet_ops);
CREATE UNIQUE INDEX IF NOT EXISTS idx_ip_whitelist_unique ON ip_whitelist (ip_address);

CREATE INDEX IF NOT EXISTS idx_raw_logs_shipper_id ON raw_logs(shipper_id);

-- Comments for documentation
COMMENT ON TABLE users IS 'User accounts with role-based access control';
COMMENT ON TABLE sessions IS 'Active user sessions for authentication';
COMMENT ON TABLE raw_logs IS 'Raw syslog messages as received from sources';
COMMENT ON TABLE parsers IS 'Custom parsers for transforming raw logs';
COMMENT ON TABLE parsed_logs IS 'Structured logs after parser processing';
COMMENT ON TABLE detection_rules IS 'YAML-based detection rules for security events';
COMMENT ON TABLE alerts IS 'Security alerts generated by detection rules';

COMMENT ON COLUMN users.role IS 'Access level: admin, analyst, viewer, or operator';
COMMENT ON COLUMN parsers.parser_type IS 'Type of parser: regex, grok, or json';
COMMENT ON COLUMN parsers.priority IS 'Parser priority (lower = higher priority)';
COMMENT ON COLUMN parsers.event_type IS 'Optional event type to assign to parsed logs (e.g., ssh_failed_login, http_request, authentik_login). If null, event type is auto-determined from parser name and extracted fields';
COMMENT ON COLUMN raw_logs.shipper_id IS 'Short identifier (8-char hash) from log shipper for tracing logs back to their source. Extracted from syslog TAG field in format tag[SHIPPERID]';
COMMENT ON COLUMN detection_rules.severity IS 'Alert severity: low, medium, high, or critical';
COMMENT ON COLUMN alerts.status IS 'Alert status: new, investigating, closed, or false_positive';

COMMENT ON TABLE ip_whitelist IS 'IP addresses whitelisted for admin interface access and rule exceptions';
COMMENT ON COLUMN ip_whitelist.ip_address IS 'IP address or CIDR block (e.g., 192.0.2.100 or 192.0.2.0/24)';
COMMENT ON COLUMN ip_whitelist.description IS 'Human-readable description of why this IP is whitelisted';
COMMENT ON COLUMN ip_whitelist.rule_id IS 'Optional: Associate whitelist entry with specific rule (e.g., AUTH-011)';
COMMENT ON COLUMN ip_whitelist.created_by IS 'User who added this whitelist entry';

-- ========================================
-- ASSET DISCOVERY & VULNERABILITY MANAGEMENT
-- ========================================

-- Audit logging for all scan operations
CREATE TABLE IF NOT EXISTS audit_logs (
    id SERIAL PRIMARY KEY,
    timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
    action VARCHAR(100) NOT NULL,
    resource_type VARCHAR(50),
    resource_id INTEGER,
    ip_address INET,
    user_agent TEXT,
    request_body JSONB,
    response_status INTEGER,
    details JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Encrypted credential storage for authenticated scanning
CREATE TABLE IF NOT EXISTS scan_credentials (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    credential_type VARCHAR(50) NOT NULL,
    username VARCHAR(255),
    encrypted_password TEXT NOT NULL,
    encryption_iv TEXT NOT NULL,
    encryption_auth_tag TEXT NOT NULL,
    encrypted_private_key TEXT,
    created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    last_rotated_at TIMESTAMPTZ,
    rotation_policy_days INTEGER DEFAULT 90,
    is_active BOOLEAN DEFAULT true
);

-- Discovered network assets
CREATE TABLE IF NOT EXISTS assets (
    id SERIAL PRIMARY KEY,
    ip_address INET NOT NULL,
    hostname VARCHAR(255),
    mac_address VARCHAR(17),
    os_type VARCHAR(100),
    os_version VARCHAR(100),
    asset_type VARCHAR(50) DEFAULT 'server',
    criticality VARCHAR(20) DEFAULT 'medium',
    status VARCHAR(20) DEFAULT 'active',
    discovery_method VARCHAR(50) DEFAULT 'nmap',
    first_seen TIMESTAMPTZ DEFAULT NOW(),
    last_seen TIMESTAMPTZ DEFAULT NOW(),
    last_scanned TIMESTAMPTZ,
    metadata JSONB,
    tags TEXT[],
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(ip_address)
);

-- Services running on assets
CREATE TABLE IF NOT EXISTS asset_services (
    id SERIAL PRIMARY KEY,
    asset_id INTEGER REFERENCES assets(id) ON DELETE CASCADE,
    port INTEGER NOT NULL,
    protocol VARCHAR(10) NOT NULL,
    service_name VARCHAR(100),
    service_version VARCHAR(255),
    state VARCHAR(20) DEFAULT 'open',
    banner TEXT,
    discovered_at TIMESTAMPTZ DEFAULT NOW(),
    last_seen TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(asset_id, port, protocol)
);

-- CVE vulnerability database
CREATE TABLE IF NOT EXISTS vulnerabilities (
    id SERIAL PRIMARY KEY,
    cve_id VARCHAR(20) UNIQUE NOT NULL,
    cvss_score NUMERIC(3,1),
    cvss_vector VARCHAR(100),
    severity VARCHAR(20),
    title VARCHAR(500),
    description TEXT,
    remediation TEXT,
    "references" TEXT[],
    published_date DATE,
    last_modified_date DATE,
    cwe_id VARCHAR(20),
    metadata JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Asset-to-vulnerability mapping
CREATE TABLE IF NOT EXISTS asset_vulnerabilities (
    id SERIAL PRIMARY KEY,
    asset_id INTEGER REFERENCES assets(id) ON DELETE CASCADE,
    vulnerability_id INTEGER REFERENCES vulnerabilities(id) ON DELETE CASCADE,
    status VARCHAR(20) DEFAULT 'open',
    risk_score NUMERIC(3,1),
    evidence TEXT,
    first_detected TIMESTAMPTZ DEFAULT NOW(),
    last_detected TIMESTAMPTZ DEFAULT NOW(),
    patched_at TIMESTAMPTZ,
    patched_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(asset_id, vulnerability_id)
);

-- Vulnerability scan history
CREATE TABLE IF NOT EXISTS vulnerability_scans (
    id SERIAL PRIMARY KEY,
    scan_type VARCHAR(50) NOT NULL,
    target VARCHAR(255) NOT NULL,
    status VARCHAR(20) DEFAULT 'queued',
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    duration_seconds INTEGER,
    assets_discovered INTEGER DEFAULT 0,
    vulnerabilities_found INTEGER DEFAULT 0,
    credential_id INTEGER REFERENCES scan_credentials(id) ON DELETE SET NULL,
    initiated_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
    scan_options JSONB,
    error_message TEXT,
    results_summary JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for Asset Discovery & Vulnerability Management
CREATE INDEX IF NOT EXISTS idx_audit_logs_timestamp ON audit_logs(timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_audit_logs_user ON audit_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_action ON audit_logs(action);
CREATE INDEX IF NOT EXISTS idx_audit_logs_resource ON audit_logs(resource_type, resource_id);

CREATE INDEX IF NOT EXISTS idx_credentials_active ON scan_credentials(is_active);
CREATE INDEX IF NOT EXISTS idx_credentials_rotation ON scan_credentials(last_rotated_at) WHERE is_active = true;

CREATE INDEX IF NOT EXISTS idx_assets_ip ON assets(ip_address);
CREATE INDEX IF NOT EXISTS idx_assets_hostname ON assets(hostname) WHERE hostname IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_assets_status ON assets(status);
CREATE INDEX IF NOT EXISTS idx_assets_criticality ON assets(criticality);
CREATE INDEX IF NOT EXISTS idx_assets_last_seen ON assets(last_seen DESC);
CREATE INDEX IF NOT EXISTS idx_assets_tags ON assets USING GIN(tags);
CREATE INDEX IF NOT EXISTS idx_assets_metadata ON assets USING GIN(metadata);

CREATE INDEX IF NOT EXISTS idx_asset_services_asset ON asset_services(asset_id);
CREATE INDEX IF NOT EXISTS idx_asset_services_port ON asset_services(port);
CREATE INDEX IF NOT EXISTS idx_asset_services_service ON asset_services(service_name);

CREATE INDEX IF NOT EXISTS idx_vulnerabilities_cve ON vulnerabilities(cve_id);
CREATE INDEX IF NOT EXISTS idx_vulnerabilities_severity ON vulnerabilities(severity);
CREATE INDEX IF NOT EXISTS idx_vulnerabilities_cvss ON vulnerabilities(cvss_score DESC);
CREATE INDEX IF NOT EXISTS idx_vulnerabilities_published ON vulnerabilities(published_date DESC);

CREATE INDEX IF NOT EXISTS idx_asset_vuln_asset ON asset_vulnerabilities(asset_id);
CREATE INDEX IF NOT EXISTS idx_asset_vuln_vulnerability ON asset_vulnerabilities(vulnerability_id);
CREATE INDEX IF NOT EXISTS idx_asset_vuln_status ON asset_vulnerabilities(status);
CREATE INDEX IF NOT EXISTS idx_asset_vuln_risk ON asset_vulnerabilities(risk_score DESC);
CREATE INDEX IF NOT EXISTS idx_asset_vuln_first_detected ON asset_vulnerabilities(first_detected DESC);

CREATE INDEX IF NOT EXISTS idx_scans_status ON vulnerability_scans(status);
CREATE INDEX IF NOT EXISTS idx_scans_started ON vulnerability_scans(started_at DESC);
CREATE INDEX IF NOT EXISTS idx_scans_type ON vulnerability_scans(scan_type);
CREATE INDEX IF NOT EXISTS idx_scans_user ON vulnerability_scans(initiated_by);

-- Triggers for auto-calculation

-- Auto-calculate scan duration
CREATE OR REPLACE FUNCTION update_scan_duration()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.completed_at IS NOT NULL AND NEW.started_at IS NOT NULL THEN
        NEW.duration_seconds := EXTRACT(EPOCH FROM (NEW.completed_at - NEW.started_at));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_scan_duration
BEFORE UPDATE ON vulnerability_scans
FOR EACH ROW
WHEN (NEW.completed_at IS NOT NULL)
EXECUTE FUNCTION update_scan_duration();

-- Auto-calculate risk score (criticality × CVSS)
CREATE OR REPLACE FUNCTION calculate_risk_score()
RETURNS TRIGGER AS $$
DECLARE
    asset_crit TEXT;
    cvss NUMERIC;
    multiplier NUMERIC;
BEGIN
    SELECT criticality INTO asset_crit FROM assets WHERE id = NEW.asset_id;
    SELECT cvss_score INTO cvss FROM vulnerabilities WHERE id = NEW.vulnerability_id;

    multiplier := CASE asset_crit
        WHEN 'critical' THEN 1.5
        WHEN 'high' THEN 1.2
        WHEN 'medium' THEN 1.0
        WHEN 'low' THEN 0.8
        ELSE 1.0
    END;

    NEW.risk_score := LEAST(10.0, cvss * multiplier);
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_risk_score
BEFORE INSERT OR UPDATE ON asset_vulnerabilities
FOR EACH ROW
EXECUTE FUNCTION calculate_risk_score();

-- Materialized view for dashboard performance
CREATE MATERIALIZED VIEW IF NOT EXISTS dashboard_vulnerability_summary AS
SELECT
    COUNT(*) FILTER (WHERE av.status = 'open' AND v.severity = 'critical') as critical_open,
    COUNT(*) FILTER (WHERE av.status = 'open' AND v.severity = 'high') as high_open,
    COUNT(*) FILTER (WHERE av.status = 'open' AND v.severity = 'medium') as medium_open,
    COUNT(*) FILTER (WHERE av.status = 'open' AND v.severity = 'low') as low_open,
    COUNT(DISTINCT av.asset_id) as affected_assets
FROM asset_vulnerabilities av
JOIN vulnerabilities v ON av.vulnerability_id = v.id
WHERE av.status = 'open';

CREATE UNIQUE INDEX IF NOT EXISTS idx_dashboard_summary ON dashboard_vulnerability_summary((true));

-- Refresh function (call from backend every 5 minutes)
CREATE OR REPLACE FUNCTION refresh_dashboard_summary()
RETURNS void AS $$
BEGIN
    REFRESH MATERIALIZED VIEW CONCURRENTLY dashboard_vulnerability_summary;
END;
$$ LANGUAGE plpgsql;

-- Comments for Asset Discovery & Vulnerability Management
COMMENT ON TABLE audit_logs IS 'Security audit trail for all scan operations, 1-year retention minimum';
COMMENT ON TABLE scan_credentials IS 'AES-256-GCM encrypted credentials for vulnerability scanning';
COMMENT ON TABLE assets IS 'Discovered network assets from NMAP scans and log correlation';
COMMENT ON TABLE asset_services IS 'Services and ports discovered on assets';
COMMENT ON TABLE vulnerabilities IS 'CVE vulnerability database from Nuclei scans';
COMMENT ON TABLE asset_vulnerabilities IS 'Vulnerabilities detected on specific assets';
COMMENT ON TABLE vulnerability_scans IS 'History of all asset discovery and vulnerability scans';

COMMENT ON COLUMN assets.asset_type IS 'Asset type: server, workstation, network, iot';
COMMENT ON COLUMN assets.criticality IS 'Business criticality: low, medium, high, critical';
COMMENT ON COLUMN assets.status IS 'Asset status: active, inactive, offline';
COMMENT ON COLUMN assets.discovery_method IS 'Discovery source: nmap, log_correlation, manual';
COMMENT ON COLUMN assets.metadata IS 'Flexible metadata storage for vendor, location, tags, custom fields';

COMMENT ON COLUMN asset_vulnerabilities.status IS 'Remediation status: open, patched, false_positive, accepted';
COMMENT ON COLUMN asset_vulnerabilities.risk_score IS 'Calculated: criticality × CVSS score';
COMMENT ON COLUMN asset_vulnerabilities.evidence IS 'Scan evidence/proof of vulnerability';

COMMENT ON COLUMN vulnerability_scans.scan_type IS 'Scan type: asset_discovery, vulnerability';
COMMENT ON COLUMN vulnerability_scans.status IS 'Scan status: queued, running, completed, failed';

-- ========================================
-- SYSTEM SETTINGS
-- ========================================

-- System settings table for configurable parameters
CREATE TABLE IF NOT EXISTS system_settings (
    id SERIAL PRIMARY KEY,
    key VARCHAR(255) UNIQUE NOT NULL,
    value TEXT NOT NULL,
    description TEXT,
    updated_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Insert default auto-discovery settings
INSERT INTO system_settings (key, value, description)
VALUES
    ('auto_discovery_enabled', 'true', 'Enable automatic asset discovery from logs'),
    ('auto_discovery_interval_minutes', '360', 'Interval in minutes between auto-discovery runs (360 = 6 hours)'),
    ('stale_asset_threshold_days', '30', 'Days before marking an asset as offline')
ON CONFLICT (key) DO NOTHING;

-- Indexes for system settings
CREATE INDEX IF NOT EXISTS idx_system_settings_key ON system_settings(key);

-- Comments for system settings
COMMENT ON TABLE system_settings IS 'System-wide configuration settings for SIEMBox';
COMMENT ON COLUMN system_settings.key IS 'Unique setting identifier';
COMMENT ON COLUMN system_settings.value IS 'Setting value stored as text (parse as needed)';
COMMENT ON COLUMN system_settings.description IS 'Human-readable description of the setting';
COMMENT ON COLUMN system_settings.updated_by IS 'User who last updated this setting';
