-- Migration 008: intentionally a no-op.
--
-- This migration used to INSERT the bundled "home-assistant" parser for existing
-- installs. SIEMBox no longer seeds hardcoded parsers/detections — a fresh
-- install starts empty and the operator installs what they want from the in-app
-- catalog (Parsers → Browse Catalog). The INSERT was removed so new installs
-- stay catalog-only.
--
-- Left as a no-op rather than deleted so the migration filename ordering and any
-- external references stay stable. Installs that already ran the old 008 keep
-- their home-assistant parser (this migration never deletes anything).
SELECT 1;
