-- Migration 009: intentionally a no-op.
--
-- This migration used to INSERT the bundled "jellyfin" and "plex" media-server
-- parsers for existing installs. SIEMBox no longer seeds hardcoded
-- parsers/detections — a fresh install starts empty and the operator installs
-- what they want from the in-app catalog (Parsers → Browse Catalog). The INSERTs
-- were removed so new installs stay catalog-only.
--
-- Left as a no-op rather than deleted so the migration filename ordering and any
-- external references stay stable. Installs that already ran the old 009 keep
-- their jellyfin/plex parsers (this migration never deletes anything).
SELECT 1;
