// GENERATED by log-shipper/build-discovery-agent.mjs -- do not edit by hand.
// Regenerate after changing the discovery probe code (see that script).
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));

// backend/src/services/logDiscovery/passiveDiscovery.ts
var dgram = __toESM(require("dgram"));
var fs = __toESM(require("fs"));
var import_child_process = require("child_process");
var import_util = require("util");

// log-shipper/discovery-agent/logger-shim.ts
var logger = {
  info: (...args) => console.error("[discovery-agent]", ...args),
  warn: (...args) => console.error("[discovery-agent]", ...args),
  error: (...args) => console.error("[discovery-agent]", ...args),
  debug: () => {
  }
};

// backend/src/services/logDiscovery/passiveDiscovery.ts
var execAsync = (0, import_util.promisify)(import_child_process.exec);
function parseProcNetArp(content) {
  const lines = content.trim().split("\n").slice(1);
  const entries = [];
  for (const line of lines) {
    const cols = line.trim().split(/\s+/);
    if (cols.length < 4) continue;
    const [ip, , flags, mac] = cols;
    if (flags === "0x0" || mac === "00:00:00:00:00:00") continue;
    entries.push({ ip, mac: mac.toLowerCase() });
  }
  return entries;
}
function parseArpCommandOutput(content) {
  const entries = [];
  const pattern = /\(([\d.]+)\)\s+at\s+([0-9a-fA-F:]{11,17})/g;
  let match;
  while (match = pattern.exec(content)) {
    entries.push({ ip: match[1], mac: match[2].toLowerCase() });
  }
  return entries;
}
async function readArpTable() {
  try {
    const content = await fs.promises.readFile("/proc/net/arp", "utf8");
    return parseProcNetArp(content);
  } catch {
  }
  try {
    const { stdout } = await execAsync("arp -a");
    return parseArpCommandOutput(stdout);
  } catch (err) {
    logger.warn(`[logDiscovery] ARP table read failed: ${err?.message || err}`);
    return [];
  }
}
var DNSMASQ_LEASE_PATHS = ["/var/lib/misc/dnsmasq.leases", "/var/db/dnsmasq.leases"];
var ISC_DHCPD_LEASE_PATHS = ["/var/lib/dhcp/dhcpd.leases", "/var/db/dhcpd.leases"];
function parseDnsmasqLeases(content) {
  const leases = [];
  for (const line of content.trim().split("\n")) {
    if (!line.trim()) continue;
    const cols = line.trim().split(/\s+/);
    if (cols.length < 4) continue;
    const [, mac, ip, hostname] = cols;
    if (!/^[0-9a-fA-F:]{17}$/.test(mac)) continue;
    leases.push({ ip, mac: mac.toLowerCase(), hostname: hostname === "*" ? void 0 : hostname });
  }
  return leases;
}
function parseIscDhcpdLeases(content) {
  const byIp = /* @__PURE__ */ new Map();
  const blockPattern = /lease\s+([\d.]+)\s*\{([^}]*)\}/g;
  let match;
  while (match = blockPattern.exec(content)) {
    const [, ip, body] = match;
    const mac = /hardware ethernet\s+([0-9a-fA-F:]{17});/.exec(body)?.[1];
    const hostname = /client-hostname\s+"([^"]*)";/.exec(body)?.[1];
    if (mac) byIp.set(ip, { ip, mac: mac.toLowerCase(), hostname });
  }
  return Array.from(byIp.values());
}
async function readDhcpLeases() {
  for (const path of DNSMASQ_LEASE_PATHS) {
    try {
      return parseDnsmasqLeases(await fs.promises.readFile(path, "utf8"));
    } catch {
    }
  }
  for (const path of ISC_DHCPD_LEASE_PATHS) {
    try {
      return parseIscDhcpdLeases(await fs.promises.readFile(path, "utf8"));
    } catch {
    }
  }
  return [];
}
var MDNS_MULTICAST_ADDR = "224.0.0.251";
var MDNS_PORT = 5353;
function buildMdnsQuery(name) {
  const header = Buffer.alloc(12);
  header.writeUInt16BE(1, 4);
  const labels = name.replace(/\.$/, "").split(".");
  const qnameParts = labels.map((label) => Buffer.concat([Buffer.from([label.length]), Buffer.from(label, "ascii")]));
  const qname = Buffer.concat([...qnameParts, Buffer.from([0])]);
  const qtypeQclass = Buffer.alloc(4);
  qtypeQclass.writeUInt16BE(12, 0);
  qtypeQclass.writeUInt16BE(1, 2);
  return Buffer.concat([header, qname, qtypeQclass]);
}
function isDnsResponse(buf) {
  if (buf.length < 4) return false;
  return (buf.readUInt16BE(2) & 32768) !== 0;
}
async function queryMdnsServices(services, opts = {}) {
  const listenMs = opts.listenMs ?? 800;
  const responders = [];
  for (const service of services) {
    const socket = dgram.createSocket({ type: "udp4", reuseAddr: true });
    try {
      await new Promise((resolve) => {
        socket.on("message", (msg, rinfo) => {
          if (isDnsResponse(msg)) responders.push({ ip: rinfo.address, service });
        });
        socket.on("error", (err) => {
          logger.warn(`[logDiscovery] mDNS query for ${service} failed: ${err.message}`);
          resolve();
        });
        socket.bind(0, () => {
          socket.send(buildMdnsQuery(`${service}.local`), MDNS_PORT, MDNS_MULTICAST_ADDR);
          setTimeout(resolve, listenMs);
        });
      });
    } finally {
      socket.close();
    }
  }
  return responders;
}
var SSDP_MULTICAST_ADDR = "239.255.255.250";
var SSDP_PORT = 1900;
function buildSsdpSearchRequest(searchTarget = "ssdp:all", mxSeconds = 2) {
  return [
    "M-SEARCH * HTTP/1.1",
    `HOST: ${SSDP_MULTICAST_ADDR}:${SSDP_PORT}`,
    'MAN: "ssdp:discover"',
    `MX: ${mxSeconds}`,
    `ST: ${searchTarget}`,
    "",
    ""
  ].join("\r\n");
}
function parseSsdpResponse(raw) {
  const headers = {};
  for (const line of raw.split("\r\n").slice(1)) {
    const idx = line.indexOf(":");
    if (idx === -1) continue;
    const key = line.slice(0, idx).trim().toLowerCase();
    const value = line.slice(idx + 1).trim();
    if (key) headers[key] = value;
  }
  return headers;
}
async function discoverSsdp(opts = {}) {
  const listenMs = opts.listenMs ?? 2e3;
  const responders = [];
  const socket = dgram.createSocket({ type: "udp4", reuseAddr: true });
  try {
    await new Promise((resolve) => {
      socket.on("message", (msg, rinfo) => {
        const headers = parseSsdpResponse(msg.toString("utf8"));
        responders.push({ ip: rinfo.address, st: headers.st, server: headers.server });
      });
      socket.on("error", (err) => {
        logger.warn(`[logDiscovery] SSDP discovery failed: ${err.message}`);
        resolve();
      });
      socket.bind(0, () => {
        socket.setBroadcast(true);
        socket.send(Buffer.from(buildSsdpSearchRequest(opts.searchTarget)), SSDP_PORT, SSDP_MULTICAST_ADDR);
        setTimeout(resolve, listenMs);
      });
    });
  } finally {
    socket.close();
  }
  return responders;
}
async function captureLldp() {
  logger.info("[logDiscovery] LLDP capture skipped: requires raw packet access not available in this deployment.");
  return [];
}

// backend/src/services/logDiscovery/activeDiscovery.ts
var net = __toESM(require("net"));
var http = __toESM(require("http"));
var https = __toESM(require("https"));
var tls = __toESM(require("tls"));

// backend/src/services/logDiscovery/scope.ts
function ipToInt(ip) {
  return ip.split(".").reduce((acc, octet) => (acc << 8) + Number(octet), 0) >>> 0;
}
function intToIp(n) {
  return [24, 16, 8, 0].map((shift) => n >>> shift & 255).join(".");
}
function cidrHosts(cidr) {
  const [base, prefixStr] = cidr.trim().split("/");
  const prefix = parseInt(prefixStr, 10);
  const hostBits = 32 - prefix;
  const size = Math.pow(2, hostBits);
  const networkInt = hostBits === 0 ? ipToInt(base) : ipToInt(base) >>> hostBits << hostBits >>> 0;
  const start = prefix >= 31 ? 0 : 1;
  const end = prefix >= 31 ? size - 1 : size - 2;
  const hosts = [];
  for (let i = start; i <= end; i++) {
    hosts.push(intToIp(networkInt + i >>> 0));
  }
  return hosts;
}

// backend/src/services/logDiscovery/activeDiscovery.ts
var MAX_BODY_BYTES = 8192;
var MAX_BANNER_BYTES = 512;
var LIVENESS_PROBE_PORTS = [80, 443, 22, 8080, 8443, 53, 3389, 9e3, 8006, 445];
function flattenHeaders(headers) {
  const flat = {};
  for (const [key, value] of Object.entries(headers)) {
    if (value === void 0) continue;
    flat[key] = Array.isArray(value) ? value.join(", ") : value;
  }
  return flat;
}
async function mapWithConcurrency(items, concurrency, fn) {
  const results = new Array(items.length);
  let next = 0;
  async function worker() {
    while (next < items.length) {
      const i = next++;
      results[i] = await fn(items[i]);
    }
  }
  await Promise.all(Array.from({ length: Math.min(concurrency, items.length) }, worker));
  return results;
}
function probeLiveness(ip, ports, timeoutMs) {
  return new Promise((resolve) => {
    if (ports.length === 0) return resolve(false);
    let remaining = ports.length;
    let resolved = false;
    const succeed = () => {
      if (resolved) return;
      resolved = true;
      resolve(true);
    };
    const fail = () => {
      if (resolved) return;
      if (--remaining === 0) {
        resolved = true;
        resolve(false);
      }
    };
    for (const port of ports) {
      const socket = new net.Socket();
      socket.setTimeout(timeoutMs);
      socket.once("connect", () => {
        socket.destroy();
        succeed();
      });
      socket.once("error", (err) => {
        socket.destroy();
        if (err.code === "ECONNREFUSED") succeed();
        else fail();
      });
      socket.once("timeout", () => {
        socket.destroy();
        fail();
      });
      socket.connect(port, ip);
    }
  });
}
async function sweepCidr(cidr, opts = {}) {
  const timeoutMs = opts.portTimeoutMs ?? 800;
  const concurrency = opts.concurrency ?? 32;
  const hosts = cidrHosts(cidr);
  const results = await mapWithConcurrency(hosts, concurrency, async (ip) => await probeLiveness(ip, LIVENESS_PROBE_PORTS, timeoutMs) ? ip : null);
  return results.filter((ip) => ip !== null);
}
function connectPort(ip, port, timeoutMs) {
  return new Promise((resolve) => {
    const socket = new net.Socket();
    let done = false;
    const finish = (result) => {
      if (done) return;
      done = true;
      socket.destroy();
      resolve(result);
    };
    socket.setTimeout(timeoutMs);
    socket.once("connect", () => finish(true));
    socket.once("timeout", () => finish(false));
    socket.once("error", () => finish(false));
    socket.connect(port, ip);
  });
}
async function tcpConnectScan(ip, ports, opts = {}) {
  const timeoutMs = opts.portTimeoutMs ?? 800;
  const concurrency = opts.concurrency ?? 8;
  const results = await mapWithConcurrency(ports, concurrency, async (port) => await connectPort(ip, port, timeoutMs) ? port : null);
  return results.filter((p) => p !== null).sort((a, b) => a - b);
}
function requestOnce(ip, port, path, useTls, timeoutMs) {
  return new Promise((resolve) => {
    const mod = useTls ? https : http;
    const requestOptions = { host: ip, port, path, method: "GET", timeout: timeoutMs, rejectUnauthorized: false };
    const req = mod.request(
      requestOptions,
      (res) => {
        let body = "";
        res.on("data", (chunk) => {
          if (body.length < MAX_BODY_BYTES) body += chunk.toString("utf8");
        });
        res.on("end", () => {
          resolve({ port, path, status: res.statusCode ?? null, body: body.slice(0, MAX_BODY_BYTES), headers: flattenHeaders(res.headers) });
        });
      }
    );
    req.on("timeout", () => req.destroy());
    req.on("error", () => resolve(null));
    req.end();
  });
}
async function httpProbe(ip, port, path, opts = {}) {
  const timeoutMs = opts.httpTimeoutMs ?? 1500;
  if (opts.forceTls === true) return requestOnce(ip, port, path, true, timeoutMs);
  if (opts.forceTls === false) return requestOnce(ip, port, path, false, timeoutMs);
  return await requestOnce(ip, port, path, false, timeoutMs) ?? await requestOnce(ip, port, path, true, timeoutMs);
}
function tlsProbe(ip, port, opts = {}) {
  const timeoutMs = opts.tlsTimeoutMs ?? 1500;
  return new Promise((resolve) => {
    let done = false;
    const finish = (result) => {
      if (done) return;
      done = true;
      resolve(result);
    };
    const connectOptions = { host: ip, port, rejectUnauthorized: false, timeout: timeoutMs };
    const socket = tls.connect(
      connectOptions,
      () => {
        const cert = socket.getPeerCertificate();
        socket.destroy();
        if (!cert || !cert.subject) return finish(null);
        const san = cert.subjectaltname ? cert.subjectaltname.split(",").map((s) => s.trim()) : void 0;
        finish({ port, subject_cn: cert.subject.CN, san });
      }
    );
    socket.once("timeout", () => {
      socket.destroy();
      finish(null);
    });
    socket.once("error", () => finish(null));
  });
}
function bannerGrab(ip, port, opts = {}) {
  const timeoutMs = opts.bannerTimeoutMs ?? 1e3;
  return new Promise((resolve) => {
    const socket = new net.Socket();
    let data = "";
    let resolved = false;
    const finish = (result) => {
      if (resolved) return;
      resolved = true;
      socket.destroy();
      resolve(result);
    };
    socket.setTimeout(timeoutMs);
    socket.on("data", (chunk) => {
      data += chunk.toString("utf8");
      finish({ port, banner: data.slice(0, MAX_BANNER_BYTES) });
    });
    socket.on("timeout", () => finish(data ? { port, banner: data.slice(0, MAX_BANNER_BYTES) } : null));
    socket.on("error", () => finish(null));
    socket.connect(port, ip);
  });
}
async function probeHostWithPlan(ip, plan, opts = {}) {
  const openPorts = await tcpConnectScan(ip, plan.ports, opts);
  const httpPaths = plan.httpPaths;
  const http_responses = [];
  const tls_subjects = [];
  const banners = [];
  for (const port of openPorts) {
    const tlsResult = await tlsProbe(ip, port, opts);
    if (tlsResult) tls_subjects.push(tlsResult);
    let gotHttp = false;
    for (const path of httpPaths) {
      const result = await httpProbe(ip, port, path, { ...opts, forceTls: tlsResult ? true : void 0 });
      if (result) {
        http_responses.push(result);
        gotHttp = true;
      }
    }
    if (!gotHttp) {
      const banner = await bannerGrab(ip, port, opts);
      if (banner) banners.push(banner);
    }
  }
  return {
    ip,
    open_ports: openPorts,
    http_responses,
    tls_subjects,
    banners,
    mdns_services: [],
    ssdp_services: [],
    discovery_methods: ["active_probe"]
  };
}

// backend/src/services/logDiscovery/probePipeline.ts
var noLog = () => {
};
function ensureCandidate(candidates, ip) {
  let c = candidates.get(ip);
  if (!c) {
    c = { ip, mdns_services: [], ssdp_services: [], discovery_methods: /* @__PURE__ */ new Set() };
    candidates.set(ip, c);
  }
  return c;
}
async function runPassivePhase(mdnsServices, log) {
  const candidates = /* @__PURE__ */ new Map();
  const ensure = (ip) => ensureCandidate(candidates, ip);
  const [arp, leases] = await Promise.all([readArpTable(), readDhcpLeases()]);
  for (const entry of arp) {
    const c = ensure(entry.ip);
    c.mac = entry.mac;
    c.discovery_methods.add("arp");
  }
  for (const lease of leases) {
    const c = ensure(lease.ip);
    c.mac = c.mac || lease.mac;
    c.hostname = c.hostname || lease.hostname;
    c.discovery_methods.add("dhcp_lease");
  }
  if (mdnsServices.length > 0) {
    const responders = await queryMdnsServices(mdnsServices).catch((err) => {
      log("warn", `mDNS phase failed: ${err?.message || err}`);
      return [];
    });
    for (const r of responders) {
      const c = ensure(r.ip);
      if (!c.mdns_services.includes(r.service)) c.mdns_services.push(r.service);
      c.discovery_methods.add("mdns");
    }
  }
  const ssdpResponders = await discoverSsdp().catch((err) => {
    log("warn", `SSDP phase failed: ${err?.message || err}`);
    return [];
  });
  for (const r of ssdpResponders) {
    const c = ensure(r.ip);
    c.ssdp_services.push({ st: r.st, server: r.server });
    c.discovery_methods.add("ssdp");
  }
  await captureLldp();
  return candidates;
}
async function runCidrSweep(cidrs, candidates, log) {
  if (cidrs.length === 0) return;
  const results = await Promise.all(
    cidrs.map(
      (cidr) => sweepCidr(cidr).catch((err) => {
        log("warn", `CIDR sweep of ${cidr} failed: ${err?.message || err}`);
        return [];
      })
    )
  );
  for (const ips of results) {
    for (const ip of ips) {
      ensureCandidate(candidates, ip).discovery_methods.add("active_sweep");
    }
  }
}
async function runActivePhase(candidates, signalsByIp, plan, log) {
  const ips = Array.from(candidates.keys());
  const concurrency = 4;
  let next = 0;
  async function worker() {
    while (next < ips.length) {
      const ip = ips[next++];
      try {
        const active = await probeHostWithPlan(ip, { ports: plan.ports, httpPaths: plan.httpPaths });
        const existing = signalsByIp.get(ip);
        if (!existing) continue;
        existing.open_ports = active.open_ports;
        existing.http_responses = active.http_responses;
        existing.tls_subjects = active.tls_subjects;
        existing.banners = active.banners;
        existing.discovery_methods = Array.from(/* @__PURE__ */ new Set([...existing.discovery_methods, ...active.discovery_methods]));
      } catch (err) {
        log("warn", `active probe of ${ip} failed: ${err?.message || err}`);
      }
    }
  }
  await Promise.all(Array.from({ length: Math.min(concurrency, ips.length) }, worker));
}
async function gatherSignals(opts) {
  const log = opts.log ?? noLog;
  const active = opts.mode === "active" || opts.mode === "full";
  const candidates = await runPassivePhase(opts.plan.mdnsServices, log);
  opts.checkCancel?.();
  if (active) {
    await runCidrSweep(opts.cidrs, candidates, log);
    opts.checkCancel?.();
  }
  const signalsByIp = /* @__PURE__ */ new Map();
  for (const [ip, c] of candidates) {
    signalsByIp.set(ip, {
      ip,
      mac: c.mac,
      hostname: c.hostname,
      open_ports: [],
      http_responses: [],
      tls_subjects: [],
      banners: [],
      mdns_services: c.mdns_services,
      ssdp_services: c.ssdp_services,
      discovery_methods: Array.from(c.discovery_methods)
    });
  }
  if (active) {
    await runActivePhase(candidates, signalsByIp, opts.plan, log);
    opts.checkCancel?.();
  }
  return Array.from(signalsByIp.values());
}

// log-shipper/discovery-agent/index.ts
async function readStdin() {
  const chunks = [];
  for await (const chunk of process.stdin) chunks.push(chunk);
  return Buffer.concat(chunks).toString("utf8");
}
function asStringArray(value) {
  return Array.isArray(value) ? value.filter((v) => typeof v === "string") : [];
}
async function main() {
  const raw = (await readStdin()).trim();
  if (!raw) throw new Error("no job on stdin");
  const job = JSON.parse(raw);
  const mode = job.mode === "passive" || job.mode === "active" || job.mode === "full" ? job.mode : "full";
  const cidrs = asStringArray(job.cidrs);
  const plan = {
    ports: Array.isArray(job?.probePlan?.ports) ? job.probePlan.ports.filter((n) => Number.isInteger(n)) : [],
    httpPaths: asStringArray(job?.probePlan?.httpPaths),
    mdnsServices: asStringArray(job?.probePlan?.mdnsServices)
  };
  const signals = await gatherSignals({
    mode,
    cidrs,
    plan,
    log: (level, message) => process.stderr.write(`[discovery-agent] ${level}: ${message}
`)
  });
  const out = JSON.stringify(signals ?? []);
  await new Promise((resolve, reject) => {
    process.stdout.write(out, (err) => err ? reject(err) : resolve());
  });
}
main().catch((err) => {
  process.stderr.write(`[discovery-agent] fatal: ${err?.message || err}
`);
  process.exit(1);
});
