version: '3.8'

services:
  config-ui:
    build: ./config-ui
    container_name: siembox-log-shipper-config-ui
    restart: unless-stopped
    ports:
      - "3002:3002"
    networks:
      - default

networks:
  default:
    driver: bridge
