name: Build and Push Docker Images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      # Build and push each service
      - name: Build and push API image
        uses: docker/build-push-action@v5
        with:
          context: ./api
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository }}/api:latest
            ${{ env.REGISTRY }}/${{ github.repository }}/api:${{ github.sha }}

      - name: Build and push Detection image
        uses: docker/build-push-action@v5
        with:
          context: ./detection
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository }}/detection:latest
            ${{ env.REGISTRY }}/${{ github.repository }}/detection:${{ github.sha }}

      - name: Build and push Collector image
        uses: docker/build-push-action@v5
        with:
          context: ./collector
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository }}/collector:latest
            ${{ env.REGISTRY }}/${{ github.repository }}/collector:${{ github.sha }}

      - name: Build and push Frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository }}/frontend:latest
            ${{ env.REGISTRY }}/${{ github.repository }}/frontend:${{ github.sha }}

      - name: Build and push IP Lookup image
        uses: docker/build-push-action@v5
        with:
          context: ./iplookup
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository }}/iplookup:latest
            ${{ env.REGISTRY }}/${{ github.repository }}/iplookup:${{ github.sha }}